version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  test:
    executor:
      name: android/android-machine
      tag: "default"
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run Local Unit Tests
          command: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results:
          path: app/build/test-results

workflows:
  build-and-test:
    jobs:
      - test
